"""Generated by mlango 0.1.0 on 2026-07-29 23:27."""

from mlango import migrations
from mlango.core import fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateObject(
            name='Helper',
            kind='agent',
            fields=[],
            options={
                'description': 'Answers questions about reviews and can call the trained classifier.',
                'max_steps': 6,
                'system': 'You help analyse product reviews. When the user gives you review text and asks for a verdict, use the classify_review tool rather than guessing.',
            },
        ),
        migrations.CreateObject(
            name='Reviews',
            kind='dataset',
            fields=[
                ('id', fields.IntegerField()),
                ('text', fields.TextField()),
                ('label', fields.LabelField(['neg', 'pos'])),
            ],
            options={
                'description': 'Synthetic product reviews, generated in code.',
                'primary_key': 'id',
            },
        ),
        migrations.CreateObject(
            name='Sentiment',
            kind='model',
            fields=[
                ('max_features', fields.IntegerField(default=5000, tunable=True, min_value=1)),
                ('C', fields.FloatField(default=1.0, tunable=True, min_value=0.0)),
            ],
            options={
                'description': 'TF-IDF features into logistic regression.',
                'features': ['text'],
                'splits': {
                    'train': 0.8,
                    'val': 0.2,
                },
                'task': 'classification',
                'trainer': 'sklearn',
            },
        ),
        migrations.CreateObject(
            name='SentimentAccuracy',
            kind='eval',
            fields=[],
            options={
                'case_id_field': 'id',
                'description': 'Does the trained classifier agree with the labels?',
                'expected_field': 'label',
                'input_field': 'text',
                'max_cases': 100,
                'threshold': 1.0,
            },
        ),
    ]
