"""Rendering operations back into a readable migration module.

Generated files are meant to be read and edited by hand, so the writer produces
ordinary formatted Python rather than a serialised blob.
"""

from __future__ import annotations

import datetime as dt
import os
import re
from typing import Any

from mlango.core.exceptions import MigrationError
from mlango.core.fields import Field
from mlango.migrations import operations as ops

MIGRATION_RE = re.compile(r"^(\d{4})_([a-zA-Z0-9_]+)\.py$")


class MigrationWriter:
    def __init__(self, app_label: str, name: str, operations: list[ops.Operation],
                 dependencies: list[tuple[str, str]], *, initial: bool = False):
        self.app_label = app_label
        self.name = name
        self.operations = operations
        self.dependencies = dependencies
        self.initial = initial
        self._imports: dict[str, str] = {}

    # -- rendering -----------------------------------------------------------

    def as_string(self) -> str:
        from mlango import __version__

        body = self._render_operations()
        imports = self._render_imports()
        stamp = dt.datetime.now().strftime("%Y-%m-%d %H:%M")

        lines = [
            f'"""Generated by mlango {__version__} on {stamp}."""',
            "",
            "from mlango import migrations",
        ]
        lines.extend(imports)
        lines += [
            "",
            "",
            "class Migration(migrations.Migration):",
            "",
        ]
        if self.initial:
            lines += ["    initial = True", ""]
        lines.append(f"    dependencies = {self._render_dependencies()}")
        lines += ["", "    operations = [", body, "    ]", ""]
        return "\n".join(lines)

    def _render_dependencies(self) -> str:
        if not self.dependencies:
            return "[]"
        rendered = ", ".join(f"({app!r}, {name!r})" for app, name in self.dependencies)
        return f"[{rendered}]"

    def _render_imports(self) -> list[str]:
        lines = []
        for module, alias in sorted(self._imports.items()):
            if module == "mlango.core.fields":
                lines.append("from mlango.core import fields")
            elif alias == module.rpartition(".")[2]:
                lines.append(f"from {module.rpartition('.')[0]} import {alias}")
            else:
                lines.append(f"import {module} as {alias}")
        return lines

    def _alias_for(self, module: str) -> str:
        if module in self._imports:
            return self._imports[module]
        candidate = module.rpartition(".")[2]
        if candidate in self._imports.values():
            candidate = module.replace(".", "_")
        self._imports[module] = candidate
        return candidate

    def _render_operations(self) -> str:
        chunks = [self._render_operation(op) for op in self.operations]
        return "\n".join(chunks)

    def _render_operation(self, operation: ops.Operation) -> str:
        name, args, kwargs = operation.deconstruct()
        if isinstance(operation, ops.RunPython):
            raise MigrationError(
                "RunPython operations are written by hand; the autodetector never "
                "generates them."
            )
        parts = [f"        migrations.{name}("]
        for value in args:
            parts.append(f"            {self._render_value(value, indent=12)},")
        for key, value in kwargs.items():
            parts.append(f"            {key}={self._render_value(value, indent=12)},")
        parts.append("        ),")
        return "\n".join(parts)

    def _render_value(self, value: Any, indent: int = 0) -> str:
        pad = " " * indent
        if isinstance(value, Field):
            return self._render_field(value)
        if isinstance(value, list):
            if not value:
                return "[]"
            if all(isinstance(v, tuple) and len(v) == 2 and isinstance(v[1], Field) for v in value):
                inner = "\n".join(
                    f"{pad}    ({name!r}, {self._render_field(field)})," for name, field in value
                )
                return "[\n" + inner + f"\n{pad}]"
            inner = ", ".join(self._render_value(v, indent + 4) for v in value)
            return f"[{inner}]"
        if isinstance(value, dict):
            if not value:
                return "{}"
            # Nested values must inherit the current indent, or a dict inside a
            # dict renders flush against the left margin.
            inner = "\n".join(
                f"{pad}    {k!r}: {self._render_value(v, indent + 4)},"
                for k, v in sorted(value.items())
            )
            return "{\n" + inner + f"\n{pad}}}"
        if isinstance(value, tuple):
            inner = ", ".join(self._render_value(v, indent + 4) for v in value)
            return f"({inner},)" if len(value) == 1 else f"({inner})"
        return repr(value)

    def _render_field(self, field: Field) -> str:
        _name, path, args, kwargs = field.deconstruct()
        module, _, class_name = path.rpartition(".")
        alias = self._alias_for(module)
        rendered_args = [self._render_value(a) for a in args]
        rendered_kwargs = [f"{k}={self._render_value(v)}" for k, v in kwargs.items()]
        joined = ", ".join(rendered_args + rendered_kwargs)
        return f"{alias}.{class_name}({joined})"

    # -- filesystem ----------------------------------------------------------

    @property
    def filename(self) -> str:
        return f"{self.name}.py"

    def write(self, directory: str) -> str:
        ensure_migrations_package(directory)
        target = os.path.join(directory, self.filename)
        with open(target, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(self.as_string())
        return target


def ensure_migrations_package(directory: str) -> None:
    os.makedirs(directory, exist_ok=True)
    init_file = os.path.join(directory, "__init__.py")
    if not os.path.exists(init_file):
        with open(init_file, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("")


def next_migration_number(directory: str) -> int:
    if not os.path.isdir(directory):
        return 1
    numbers = [
        int(match.group(1))
        for filename in os.listdir(directory)
        if (match := MIGRATION_RE.match(filename))
    ]
    return max(numbers, default=0) + 1


def build_filename(number: int, name: str) -> str:
    return f"{number:04d}_{name}"
