"""Generated by mlango 0.1.0 on 2026-07-30 23:59."""

from mlango import migrations
from mlango.core import fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateObject(
            name="Posts",
            kind="dataset",
            fields=[
                ("id", fields.IntegerField()),
                ("text", fields.TextField()),
                (
                    "group",
                    fields.LabelField(
                        ["alt.atheism", "comp.graphics", "sci.med", "soc.religion.christian"]
                    ),
                ),
            ],
            options={
                "description": "Usenet posts from four newsgroups, labelled by group.",
                "homepage": "http://qwone.com/~jason/20Newsgroups/",
                "license": "public domain",
                "primary_key": "id",
            },
        ),
        migrations.CreateObject(
            name="Topic",
            kind="model",
            fields=[
                ("max_features", fields.IntegerField(default=50000, tunable=True, min_value=1)),
                (
                    "ngram_max",
                    fields.IntegerField(default=2, tunable=True, min_value=1, max_value=3),
                ),
                ("min_df", fields.IntegerField(default=2, tunable=True, min_value=1)),
                ("C", fields.FloatField(default=4.0, tunable=True, min_value=0.0)),
            ],
            options={
                "description": "TF-IDF over the post body, into logistic regression.",
                "features": ["text"],
                "monitor": "accuracy",
                "monitor_mode": "max",
                "splits": {
                    "train": 0.8,
                    "val": 0.2,
                },
                "task": "classification",
                "trainer": "sklearn",
            },
        ),
        migrations.CreateObject(
            name="TopicAccuracy",
            kind="eval",
            fields=[],
            options={
                "case_id_field": "id",
                "description": "Does the classifier put a post in the group it came from?",
                "expected_field": "group",
                "input_field": "text",
                "max_cases": 500,
                "threshold": 0.8,
            },
        ),
    ]
